kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codewind-binding
subjects:
- kind: Group
  name: system:serviceaccounts:<namespace>:che-workspace
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eclipse-codewind
  apiGroup: rbac.authorization.k8s.io